kdsoap: Autospec creation for update from version 2.1.1 to version 2.2.0
Aleš Petrovački (6):
      Add new KDSoap logo
      Add new Logo
      Add KDSoap trademark
      Update logo and trademark
      Update README.md
      Update README.md

Allen Winter (29):
      open for version 2.2.0
      open for a possible 2.1.2 release
      .pre-commint-config.yaml - update hooks versions
      move to clangformat v14
      appveyor.yml - use qt6.3 on Mac (qt6.1 is no longer supported)
      .pre-commit-config.yaml - autoupdate
      appveyor.yml - move to macos-monterey image
      update copyright year to 2023
      .mdlrc.rb -  don't require first line to be a header
      .pre-commit-config.yaml - autoupdate
      various - clang-format v15 fixes
      src/KDSoapServer/KDSoapServerThread.cpp - clang-format skip
      README.md - we don't offer commercial license any longer
      README.md - fix typo
      appveyor.yml - add export CTEST_OUTPUT_ON_FAILURE=1
      appveyor.yml - remove Mac from the build matrix
      cmake/ECM/modules/ECMQueryQt.cmake - upstream fix for qt6
      .pre-commit-config.yaml - autoupdate
      src/KDSoapServer/KDSoapServerSocket.cpp - fix spelling
      .pre-commit-config.yaml - autoupdate and add a few more hooks
      src/KDSoapClient/CMakeLists.txt - minor cmake-format
      CMakeLists.txt - minor cmake-format fix
      Modify the copyright line to show the file creation year only
      docs/api/Doxyfile.cmake - modernize for doxygen 1.9.8
      replace Qt_VERSION_MAJOR with the more standard QT_VERSION_MAJOR
      Install the Windows pdb files in the bin dir
      Sync extra cmake from upstream KDE and KDAB (#279)
      .clazy - don't run the fully-qualified-moc-types checker
      distro/ - prep for 2.2.0 release

Daniel Nicoletti (8):
      Add GitHub actions (#266)
      CI: Updates to dedup KDAB CI
      CI: Add static analysis at night
      CI: Use Qt6 when nightly testing
      CI: Remove code to force nightly runs
      CI: Fix license
      CI for kdsoap-2.2 (#275)
      CI disable kdsoap-test_wsdl_rpc as it's flacky (#277)

David Faure (40):
      remove unused import statement in WSDL
      Fix compilation with C++17 on mac, std::random_shuffle is gone
      Slightly more readable variable name
      Revert "buildsystem - Qt6 build - install includes into "-qt6" dirs"
      clang-tidy fix (unused variable)
      Fix cppcheck warnings
      Updated clearbooks WSDL file from https://secure.clearbooks.co.uk/api/accounting/wsdl
      Add KDSoapClientInterface::setMessageAddressingProperties()
      fix -Wdocumentation warning
      Fix -import-path for kdwsdl2cpp by using the import path in more places
      Don't require a SOAP action in order to write addressing properties.
      Some clazy fixes
      More clazy fixes (parent qobject arg, qgetenv.toInt)
      cppcheck fixes
      More clazy fixes
      Update libkode, to reduce verbosity on parser errors
      revert previous commit, I confused the libkode forks
      More clazy fixes
      Update libkode to reduce verbosity on errors
      Fix clazy warning about non-POD static QName
      Better fix for XmlAnyType() that doesn't require C++17
      Fix "Polymorphic class KWSDL::AbstractBinding is copyable. Potential slicing."
      Fix copyable base interface classes
      More clazy exclusions for the QObject parent check
      Final clazy fixes
      Ensure KDSoapConfig.cmake finds Qt first.
      clazy fix ("Signature is not normalized")
      Remove KDSoapMessage::isNull(), same implementation as KDSoapValue::isNil()
      Attempt to silence a cppcheck warning
      Fix Qt6 compilation warnings around QVariant/QMetaType
      Fix cppcheck silencing comment
      Turn writeXML assert into a qWarning
      Increase timeout, Windows CI is slow
      KDSoapUdpClient: use a single socket for IPv4 and IPv6
      Fixes suggested by Coverity (mostly std::move)
      Remove outdated cppcheck suppression
      Generate forwarding headers also when used as a git submodule
      Only call feature_summary when not a submodule
      reformat with cmake-format, good bye nice readable indentation
      Add ALIAS to match the exported target. Useful when used as a git submodule.

David Werner (1):
      Fix compiler error C1061 when using more than 122 functions

Joshua Goins (1):
      Fix Qt5-Qt6 co-install

Krzysztof Kotlenga (1):
      Remove stray ":" in .prf file

Volker Krause (1):
      Export KDQName debug stream operator

pre-commit-ci[bot] (3):
      [pre-commit.ci] pre-commit autoupdate (#250)
      [pre-commit.ci] pre-commit autoupdate (#252)
      [pre-commit.ci] pre-commit autoupdate (#257)